---
- name: For Jenkins-Master server
  hosts: jenkins
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        upgrade: yes
        update_cache: yes
    - name: install git
      apt: 
        name: git-all
        state: present
    - name: Update apt package cache
      apt:
        upgrade: yes
        update_cache: yes
    - name: download jenkins supporting files
      shell: | 
        sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \ https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \  /etc/apt/sources.list.d/jenkins.list > /dev/null
#      args:
#        chdir: /home/ubuntu/
    - name: Update apt package cache
      apt:
        upgrade: yes
        update_cache: yes
    - name: install java
      apt: 
        name: openjdk-17-jre
        state: present
    - name: install jenkins
      apt:
        name: jenkins
        state: present
#      shell: sudo apt-get install jenkins -y
    - name: set varibale path for java
      shell: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$PATH:$JAVA_HOME/bin
        echo $PATH
- name: For Minikube-docker server
  hosts: minikube
#   become: true
  tasks:
    - name: Update apt package cache
      become: true
      apt:
        upgrade: yes
#        update_cache: yes
    - name: install java for jenkins job to run
      become: true
      apt:
        name: openjdk-17-jre
        state: present
        update_cache: true
    - name: Update apt package cache
      become: true
      apt:
        upgrade: yes
    - name: Add the official Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y
    - name: install docker enterprise
      become: true
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true
    - name: Add current user in docker and installing required packages for minikube
      shell: |
        sudo usermod -aG docker $USER && newgrp docker
        wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo cp minikube-linux-amd64 /usr/local/bin/minikube
        sudo chmod +x /usr/local/bin/minikube
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
      args:
        chdir: /home/ubuntu/
